name = "zmqtest"
uuid = "7f123a7e-1cc0-4cf1-8281-d763fb0b5944"
authors = ["Jesper Wendel Devantier <jwd@defmacro.it> and contributors"]
version = "0.1.0"

[deps]
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
ZeroMQ_jll = "8f1865be-045e-5c20-9c9f-bfbfb0764568"

[compat]
ZMQ = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
